//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanExchange.Presentation.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanExchange.Presentation.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string AboutForm_Copyright {
            get {
                return ResourceManager.GetString("AboutForm_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string AboutForm_License {
            get {
                return ResourceManager.GetString("AboutForm_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the MIT license..
        /// </summary>
        internal static string AboutForm_MIT {
            get {
                return ResourceManager.GetString("AboutForm_MIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins:.
        /// </summary>
        internal static string AboutForm_Plugins {
            get {
                return ResourceManager.GetString("AboutForm_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About «{0}».
        /// </summary>
        internal static string AboutForm_Title {
            get {
                return ResourceManager.GetString("AboutForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutForm_Version {
            get {
                return ResourceManager.GetString("AboutForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage.
        /// </summary>
        internal static string AboutForm_Webpage {
            get {
                return ResourceManager.GetString("AboutForm_Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_16 {
            get {
                object obj = ResourceManager.GetObject("back_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_32 {
            get {
                object obj = ResourceManager.GetObject("back_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the availability of the resource....
        /// </summary>
        internal static string Checking_the_availability {
            get {
                return ResourceManager.GetString("Checking_the_availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_hover {
            get {
                object obj = ResourceManager.GetObject("clear_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_normal {
            get {
                object obj = ResourceManager.GetObject("clear_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     .
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        internal static string KeyCtrlC {
            get {
                return ResourceManager.GetString("KeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected items.
        /// </summary>
        internal static string KeyCtrlC_ {
            get {
                return ResourceManager.GetString("KeyCtrlC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlC__ {
            get {
                return ResourceManager.GetString("KeyCtrlC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string KeyDel {
            get {
                return ResourceManager.GetString("KeyDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item(s) which was created by user..
        /// </summary>
        internal static string KeyDel__ {
            get {
                return ResourceManager.GetString("KeyDel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LanExchange_48x48 {
            get {
                object obj = ResourceManager.GetObject("LanExchange_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MainForm_Close {
            get {
                return ResourceManager.GetString("MainForm_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tabs.
        /// </summary>
        internal static string mCloseOther_Text {
            get {
                return ResourceManager.GetString("mCloseOther_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tabs.
        /// </summary>
        internal static string mCloseOther_Text1 {
            get {
                return ResourceManager.GetString("mCloseOther_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string mCloseTab_Text {
            get {
                return ResourceManager.GetString("mCloseTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string mCloseTab_Text1 {
            get {
                return ResourceManager.GetString("mCloseTab_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string mCopyMenu_Text {
            get {
                return ResourceManager.GetString("mCopyMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string mDelete_Text {
            get {
                return ResourceManager.GetString("mDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string mExit_Text {
            get {
                return ResourceManager.GetString("mExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string mHelp_Text {
            get {
                return ResourceManager.GetString("mHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string mHelpAbout_Text {
            get {
                return ResourceManager.GetString("mHelpAbout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BugTracker Webpage.
        /// </summary>
        internal static string mHelpBugs_Text {
            get {
                return ResourceManager.GetString("mHelpBugs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Keys.
        /// </summary>
        internal static string mHelpKeys_Text {
            get {
                return ResourceManager.GetString("mHelpKeys_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Webpage.
        /// </summary>
        internal static string mHelpLangs_Text {
            get {
                return ResourceManager.GetString("mHelpLangs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanExchange Webpage.
        /// </summary>
        internal static string mHelpWeb_Text {
            get {
                return ResourceManager.GetString("mHelpWeb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        internal static string mLanguage_Text {
            get {
                return ResourceManager.GetString("mLanguage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string mNewItem_Text {
            get {
                return ResourceManager.GetString("mNewItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Panel.
        /// </summary>
        internal static string mPanel_Text {
            get {
                return ResourceManager.GetString("mPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string mPaste_Text {
            get {
                return ResourceManager.GetString("mPaste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-read.
        /// </summary>
        internal static string mReRead_Text {
            get {
                return ResourceManager.GetString("mReRead_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-read.
        /// </summary>
        internal static string mReRead_Text1 {
            get {
                return ResourceManager.GetString("mReRead_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string mTrayAbout_Text {
            get {
                return ResourceManager.GetString("mTrayAbout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string mTrayExit_Text {
            get {
                return ResourceManager.GetString("mTrayExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string mTrayOpen_Text {
            get {
                return ResourceManager.GetString("mTrayOpen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string mView_Text {
            get {
                return ResourceManager.GetString("mView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string mViewDetails_Text {
            get {
                return ResourceManager.GetString("mViewDetails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid lines.
        /// </summary>
        internal static string mViewGrid_Text {
            get {
                return ResourceManager.GetString("mViewGrid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info panel.
        /// </summary>
        internal static string mViewInfo_Text {
            get {
                return ResourceManager.GetString("mViewInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large icons.
        /// </summary>
        internal static string mViewLarge_Text {
            get {
                return ResourceManager.GetString("mViewLarge_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string mViewList_Text {
            get {
                return ResourceManager.GetString("mViewList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small icons.
        /// </summary>
        internal static string mViewSmall_Text {
            get {
                return ResourceManager.GetString("mViewSmall_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open tab «{0}».
        /// </summary>
        internal static string PagesView_OpenTab {
            get {
                return ResourceManager.GetString("PagesView_OpenTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy «{0}».
        /// </summary>
        internal static string PanelView_CopyColumn {
            get {
                return ResourceManager.GetString("PanelView_CopyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to «{0}».
        /// </summary>
        internal static string PanelView_CopyPathTo {
            get {
                return ResourceManager.GetString("PanelView_CopyPathTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item.
        /// </summary>
        internal static string PanelView_CopySelected {
            get {
                return ResourceManager.GetString("PanelView_CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} selected items.
        /// </summary>
        internal static string PanelView_CopySelectedPlural {
            get {
                return ResourceManager.GetString("PanelView_CopySelectedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution error.
        /// </summary>
        internal static string PanelView_RunCmdErrorCaption {
            get {
                return ResourceManager.GetString("PanelView_RunCmdErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute command line:
        ///{0}.
        /// </summary>
        internal static string PanelView_RunCmdErrorMsg {
            get {
                return ResourceManager.GetString("PanelView_RunCmdErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_16 {
            get {
                object obj = ResourceManager.GetObject("user_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_32 {
            get {
                object obj = ResourceManager.GetObject("user_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
