//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanExchange.Presentation.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanExchange.Presentation.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_hover {
            get {
                object obj = ResourceManager.GetObject("clear_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_normal {
            get {
                object obj = ResourceManager.GetObject("clear_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     .
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        internal static string KeyCtrlC {
            get {
                return ResourceManager.GetString("KeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected items.
        /// </summary>
        internal static string KeyCtrlC_ {
            get {
                return ResourceManager.GetString("KeyCtrlC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlC__ {
            get {
                return ResourceManager.GetString("KeyCtrlC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string KeyDel {
            get {
                return ResourceManager.GetString("KeyDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item(s) which was created by user..
        /// </summary>
        internal static string KeyDel__ {
            get {
                return ResourceManager.GetString("KeyDel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tabs.
        /// </summary>
        internal static string mCloseOther_Text {
            get {
                return ResourceManager.GetString("mCloseOther_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string mCloseTab_Text {
            get {
                return ResourceManager.GetString("mCloseTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string mCopyMenu_Text {
            get {
                return ResourceManager.GetString("mCopyMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string mDelete_Text {
            get {
                return ResourceManager.GetString("mDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string mPaste_Text {
            get {
                return ResourceManager.GetString("mPaste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-read.
        /// </summary>
        internal static string mReRead_Text {
            get {
                return ResourceManager.GetString("mReRead_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open tab «{0}».
        /// </summary>
        internal static string PagesView_OpenTab {
            get {
                return ResourceManager.GetString("PagesView_OpenTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy «{0}».
        /// </summary>
        internal static string PanelView_CopyColumn {
            get {
                return ResourceManager.GetString("PanelView_CopyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to «{0}».
        /// </summary>
        internal static string PanelView_CopyPathTo {
            get {
                return ResourceManager.GetString("PanelView_CopyPathTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item.
        /// </summary>
        internal static string PanelView_CopySelected {
            get {
                return ResourceManager.GetString("PanelView_CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} selected items.
        /// </summary>
        internal static string PanelView_CopySelectedPlural {
            get {
                return ResourceManager.GetString("PanelView_CopySelectedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution error.
        /// </summary>
        internal static string PanelView_RunCmdErrorCaption {
            get {
                return ResourceManager.GetString("PanelView_RunCmdErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute command line:
        ///{0}.
        /// </summary>
        internal static string PanelView_RunCmdErrorMsg {
            get {
                return ResourceManager.GetString("PanelView_RunCmdErrorMsg", resourceCulture);
            }
        }
    }
}
