//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanExchange.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanExchange.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string AboutForm_Copyright {
            get {
                return ResourceManager.GetString("AboutForm_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string AboutForm_License {
            get {
                return ResourceManager.GetString("AboutForm_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the MIT license..
        /// </summary>
        internal static string AboutForm_MIT {
            get {
                return ResourceManager.GetString("AboutForm_MIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins:.
        /// </summary>
        internal static string AboutForm_Plugins {
            get {
                return ResourceManager.GetString("AboutForm_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About «{0}».
        /// </summary>
        internal static string AboutForm_Title {
            get {
                return ResourceManager.GetString("AboutForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations:.
        /// </summary>
        internal static string AboutForm_Translations {
            get {
                return ResourceManager.GetString("AboutForm_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutForm_Version {
            get {
                return ResourceManager.GetString("AboutForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage.
        /// </summary>
        internal static string AboutForm_Webpage {
            get {
                return ResourceManager.GetString("AboutForm_Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (build {0}).
        /// </summary>
        internal static string AboutInfo_Build {
            get {
                return ResourceManager.GetString("AboutInfo_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap back_16 {
            get {
                object obj = ResourceManager.GetObject("back_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_32 {
            get {
                object obj = ResourceManager.GetObject("back_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear_hover {
            get {
                object obj = ResourceManager.GetObject("clear_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear_normal {
            get {
                object obj = ResourceManager.GetObject("clear_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap email_icon {
            get {
                object obj = ResourceManager.GetObject("email_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     .
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input text must not be empty..
        /// </summary>
        internal static string InputBoxPresenter_NotEmpty {
            get {
                return ResourceManager.GetString("InputBoxPresenter_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab with specified name already exists..
        /// </summary>
        internal static string InputBoxPresenter_TabNameAlreadyExists {
            get {
                return ResourceManager.GetString("InputBoxPresenter_TabNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any char.
        /// </summary>
        internal static string KeyAnyChar {
            get {
                return ResourceManager.GetString("KeyAnyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter panel items by all columns..
        /// </summary>
        internal static string KeyAnyChar__ {
            get {
                return ResourceManager.GetString("KeyAnyChar__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        internal static string KeyBackspace {
            get {
                return ResourceManager.GetString("KeyBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go level up in panel..
        /// </summary>
        internal static string KeyBackspace__ {
            get {
                return ResourceManager.GetString("KeyBackspace__", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap keyboard_16 {
            get {
                object obj = ResourceManager.GetObject("keyboard_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+A.
        /// </summary>
        internal static string KeyCtrlA {
            get {
                return ResourceManager.GetString("KeyCtrlA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all items in panel..
        /// </summary>
        internal static string KeyCtrlA__ {
            get {
                return ResourceManager.GetString("KeyCtrlA__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Ins.
        /// </summary>
        internal static string KeyCtrlAltIns {
            get {
                return ResourceManager.GetString("KeyCtrlAltIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full path of selected item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlAltIns__ {
            get {
                return ResourceManager.GetString("KeyCtrlAltIns__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        internal static string KeyCtrlC {
            get {
                return ResourceManager.GetString("KeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected items.
        /// </summary>
        internal static string KeyCtrlC_ {
            get {
                return ResourceManager.GetString("KeyCtrlC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlC__ {
            get {
                return ResourceManager.GetString("KeyCtrlC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Down.
        /// </summary>
        internal static string KeyCtrlDown {
            get {
                return ResourceManager.GetString("KeyCtrlDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase height of info panel or show it..
        /// </summary>
        internal static string KeyCtrlDown__ {
            get {
                return ResourceManager.GetString("KeyCtrlDown__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Ins.
        /// </summary>
        internal static string KeyCtrlIns {
            get {
                return ResourceManager.GetString("KeyCtrlIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy column on which the ordered item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlIns__ {
            get {
                return ResourceManager.GetString("KeyCtrlIns__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+R.
        /// </summary>
        internal static string KeyCtrlR {
            get {
                return ResourceManager.GetString("KeyCtrlR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-read.
        /// </summary>
        internal static string KeyCtrlR_ {
            get {
                return ResourceManager.GetString("KeyCtrlR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-read panel..
        /// </summary>
        internal static string KeyCtrlR__ {
            get {
                return ResourceManager.GetString("KeyCtrlR__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+T.
        /// </summary>
        internal static string KeyCtrlShiftT {
            get {
                return ResourceManager.GetString("KeyCtrlShiftT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to new tab.
        /// </summary>
        internal static string KeyCtrlShiftT_ {
            get {
                return ResourceManager.GetString("KeyCtrlShiftT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send selected item(s) to new tab..
        /// </summary>
        internal static string KeyCtrlShiftT__ {
            get {
                return ResourceManager.GetString("KeyCtrlShiftT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Up.
        /// </summary>
        internal static string KeyCtrlUp {
            get {
                return ResourceManager.GetString("KeyCtrlUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease height of info panel or hide it..
        /// </summary>
        internal static string KeyCtrlUp__ {
            get {
                return ResourceManager.GetString("KeyCtrlUp__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        internal static string KeyCtrlV {
            get {
                return ResourceManager.GetString("KeyCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string KeyCtrlV_ {
            get {
                return ResourceManager.GetString("KeyCtrlV_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste items from clipboard..
        /// </summary>
        internal static string KeyCtrlV__ {
            get {
                return ResourceManager.GetString("KeyCtrlV__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+W.
        /// </summary>
        internal static string KeyCtrlW {
            get {
                return ResourceManager.GetString("KeyCtrlW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string KeyCtrlW_ {
            get {
                return ResourceManager.GetString("KeyCtrlW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current tab..
        /// </summary>
        internal static string KeyCtrlW__ {
            get {
                return ResourceManager.GetString("KeyCtrlW__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Win+X.
        /// </summary>
        internal static string KeyCtrlWinX {
            get {
                return ResourceManager.GetString("KeyCtrlWinX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide main window..
        /// </summary>
        internal static string KeyCtrlWinX__ {
            get {
                return ResourceManager.GetString("KeyCtrlWinX__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string KeyDel {
            get {
                return ResourceManager.GetString("KeyDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string KeyDel_ {
            get {
                return ResourceManager.GetString("KeyDel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item(s) which was created by user..
        /// </summary>
        internal static string KeyDel__ {
            get {
                return ResourceManager.GetString("KeyDel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        internal static string KeyEsc {
            get {
                return ResourceManager.GetString("KeyEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter OR go level up OR hide main window..
        /// </summary>
        internal static string KeyEsc__ {
            get {
                return ResourceManager.GetString("KeyEsc__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc (long press).
        /// </summary>
        internal static string KeyEscLong {
            get {
                return ResourceManager.GetString("KeyEscLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide main window..
        /// </summary>
        internal static string KeyEscLong__ {
            get {
                return ResourceManager.GetString("KeyEscLong__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string KeyF1 {
            get {
                return ResourceManager.GetString("KeyF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Keys.
        /// </summary>
        internal static string KeyF1_ {
            get {
                return ResourceManager.GetString("KeyF1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This help on shortcuts..
        /// </summary>
        internal static string KeyF1__ {
            get {
                return ResourceManager.GetString("KeyF1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10.
        /// </summary>
        internal static string KeyF10 {
            get {
                return ResourceManager.GetString("KeyF10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string KeyF10_ {
            get {
                return ResourceManager.GetString("KeyF10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit from LanExchange program..
        /// </summary>
        internal static string KeyF10__ {
            get {
                return ResourceManager.GetString("KeyF10__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        internal static string KeyF9 {
            get {
                return ResourceManager.GetString("KeyF9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide main menu..
        /// </summary>
        internal static string KeyF9__ {
            get {
                return ResourceManager.GetString("KeyF9__", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LanExchange_48x48 {
            get {
                object obj = ResourceManager.GetObject("LanExchange_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainForm_About {
            get {
                return ResourceManager.GetString("MainForm_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MainForm_Close {
            get {
                return ResourceManager.GetString("MainForm_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainForm_Exit {
            get {
                return ResourceManager.GetString("MainForm_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid lines.
        /// </summary>
        internal static string MainForm_GridLines {
            get {
                return ResourceManager.GetString("MainForm_GridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info panel.
        /// </summary>
        internal static string MainForm_InfoPanel {
            get {
                return ResourceManager.GetString("MainForm_InfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MainForm_Information {
            get {
                return ResourceManager.GetString("MainForm_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        internal static string MainForm_Language {
            get {
                return ResourceManager.GetString("MainForm_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string MainForm_Legend {
            get {
                return ResourceManager.GetString("MainForm_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MainForm_Open {
            get {
                return ResourceManager.GetString("MainForm_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string MainForm_View {
            get {
                return ResourceManager.GetString("MainForm_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BugTracker Webpage.
        /// </summary>
        internal static string MenuBugtrackerPage {
            get {
                return ResourceManager.GetString("MenuBugtrackerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanExchange Webpage.
        /// </summary>
        internal static string MenuHomePage {
            get {
                return ResourceManager.GetString("MenuHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Webpage.
        /// </summary>
        internal static string MenuLocalizationPage {
            get {
                return ResourceManager.GetString("MenuLocalizationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Panel.
        /// </summary>
        internal static string MenuPanel {
            get {
                return ResourceManager.GetString("MenuPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of {0}.
        /// </summary>
        internal static string PagesModel_CopyOf {
            get {
                return ResourceManager.GetString("PagesModel_CopyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ({0}) of {1}.
        /// </summary>
        internal static string PagesModel_CopyOfMany {
            get {
                return ResourceManager.GetString("PagesModel_CopyOfMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tab name.
        /// </summary>
        internal static string PagesPresenter_EnterTabName {
            get {
                return ResourceManager.GetString("PagesPresenter_EnterTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        internal static string PagesPresenter_NewTab {
            get {
                return ResourceManager.GetString("PagesPresenter_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename tab.
        /// </summary>
        internal static string PagesPresenter_RenameTab {
            get {
                return ResourceManager.GetString("PagesPresenter_RenameTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab name.
        /// </summary>
        internal static string PagesPresenter_TabName {
            get {
                return ResourceManager.GetString("PagesPresenter_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab properties.
        /// </summary>
        internal static string PagesPresenter_TabProperties {
            get {
                return ResourceManager.GetString("PagesPresenter_TabProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tabs.
        /// </summary>
        internal static string PagesView_CloseOtherTabs {
            get {
                return ResourceManager.GetString("PagesView_CloseOtherTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string PagesView_CloseTab {
            get {
                return ResourceManager.GetString("PagesView_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open tab «{0}».
        /// </summary>
        internal static string PagesView_OpenTab {
            get {
                return ResourceManager.GetString("PagesView_OpenTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}.
        /// </summary>
        internal static string PanelPresenter_Items1 {
            get {
                return ResourceManager.GetString("PanelPresenter_Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0} of {1}.
        /// </summary>
        internal static string PanelPresenter_Items2 {
            get {
                return ResourceManager.GetString("PanelPresenter_Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string PanelPresenter_QueryCaption {
            get {
                return ResourceManager.GetString("PanelPresenter_QueryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource «{0}» not reachable.
        ///Continue anyway?.
        /// </summary>
        internal static string PanelPresenter_UnreachableMsg {
            get {
                return ResourceManager.GetString("PanelPresenter_UnreachableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy «{0}».
        /// </summary>
        internal static string PanelView_CopyColumn {
            get {
                return ResourceManager.GetString("PanelView_CopyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to «{0}».
        /// </summary>
        internal static string PanelView_CopyPathTo {
            get {
                return ResourceManager.GetString("PanelView_CopyPathTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item.
        /// </summary>
        internal static string PanelView_CopySelected {
            get {
                return ResourceManager.GetString("PanelView_CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} selected items.
        /// </summary>
        internal static string PanelView_CopySelectedPlural {
            get {
                return ResourceManager.GetString("PanelView_CopySelectedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution error.
        /// </summary>
        internal static string PanelView_RunCmdErrorCaption {
            get {
                return ResourceManager.GetString("PanelView_RunCmdErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute command line:
        ///{0}.
        /// </summary>
        internal static string PanelView_RunCmdErrorMsg {
            get {
                return ResourceManager.GetString("PanelView_RunCmdErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Program_Error {
            get {
                return ResourceManager.GetString("Program_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Settings_Plugins {
            get {
                return ResourceManager.GetString("Settings_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap twitter_icon {
            get {
                object obj = ResourceManager.GetObject("twitter_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_16 {
            get {
                object obj = ResourceManager.GetObject("user_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_32 {
            get {
                object obj = ResourceManager.GetObject("user_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large icons.
        /// </summary>
        internal static string ViewLargeIcons {
            get {
                return ResourceManager.GetString("ViewLargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ViewList {
            get {
                return ResourceManager.GetString("ViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small icons.
        /// </summary>
        internal static string ViewSmallIcons {
            get {
                return ResourceManager.GetString("ViewSmallIcons", resourceCulture);
            }
        }
    }
}
