//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanExchange.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanExchange.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations:.
        /// </summary>
        internal static string AboutForm_Translations {
            get {
                return ResourceManager.GetString("AboutForm_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (build {0}).
        /// </summary>
        internal static string AboutInfo_Build {
            get {
                return ResourceManager.GetString("AboutInfo_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     .
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any char.
        /// </summary>
        internal static string KeyAnyChar {
            get {
                return ResourceManager.GetString("KeyAnyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter panel items by all columns..
        /// </summary>
        internal static string KeyAnyChar__ {
            get {
                return ResourceManager.GetString("KeyAnyChar__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any char.
        /// </summary>
        internal static string KeyAnyChar1 {
            get {
                return ResourceManager.GetString("KeyAnyChar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        internal static string KeyBackspace {
            get {
                return ResourceManager.GetString("KeyBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go level up in panel..
        /// </summary>
        internal static string KeyBackspace__ {
            get {
                return ResourceManager.GetString("KeyBackspace__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard_16 {
            get {
                object obj = ResourceManager.GetObject("keyboard_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+A.
        /// </summary>
        internal static string KeyCtrlA {
            get {
                return ResourceManager.GetString("KeyCtrlA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all items in panel..
        /// </summary>
        internal static string KeyCtrlA__ {
            get {
                return ResourceManager.GetString("KeyCtrlA__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Alt+Ins.
        /// </summary>
        internal static string KeyCtrlAltIns {
            get {
                return ResourceManager.GetString("KeyCtrlAltIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full path of selected item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlAltIns__ {
            get {
                return ResourceManager.GetString("KeyCtrlAltIns__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        internal static string KeyCtrlC {
            get {
                return ResourceManager.GetString("KeyCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected items.
        /// </summary>
        internal static string KeyCtrlC_ {
            get {
                return ResourceManager.GetString("KeyCtrlC_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlC__ {
            get {
                return ResourceManager.GetString("KeyCtrlC__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Down.
        /// </summary>
        internal static string KeyCtrlDown {
            get {
                return ResourceManager.GetString("KeyCtrlDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase height of info panel or show it..
        /// </summary>
        internal static string KeyCtrlDown__ {
            get {
                return ResourceManager.GetString("KeyCtrlDown__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Down.
        /// </summary>
        internal static string KeyCtrlDown1 {
            get {
                return ResourceManager.GetString("KeyCtrlDown1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Ins.
        /// </summary>
        internal static string KeyCtrlIns {
            get {
                return ResourceManager.GetString("KeyCtrlIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy column on which the ordered item(s) to clipboard..
        /// </summary>
        internal static string KeyCtrlIns__ {
            get {
                return ResourceManager.GetString("KeyCtrlIns__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Ins.
        /// </summary>
        internal static string KeyCtrlIns1 {
            get {
                return ResourceManager.GetString("KeyCtrlIns1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+R.
        /// </summary>
        internal static string KeyCtrlR {
            get {
                return ResourceManager.GetString("KeyCtrlR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-read panel..
        /// </summary>
        internal static string KeyCtrlR__ {
            get {
                return ResourceManager.GetString("KeyCtrlR__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+R.
        /// </summary>
        internal static string KeyCtrlR1 {
            get {
                return ResourceManager.GetString("KeyCtrlR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Up.
        /// </summary>
        internal static string KeyCtrlUp {
            get {
                return ResourceManager.GetString("KeyCtrlUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease height of info panel or hide it..
        /// </summary>
        internal static string KeyCtrlUp__ {
            get {
                return ResourceManager.GetString("KeyCtrlUp__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Up.
        /// </summary>
        internal static string KeyCtrlUp1 {
            get {
                return ResourceManager.GetString("KeyCtrlUp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        internal static string KeyCtrlV {
            get {
                return ResourceManager.GetString("KeyCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste items from clipboard..
        /// </summary>
        internal static string KeyCtrlV__ {
            get {
                return ResourceManager.GetString("KeyCtrlV__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        internal static string KeyCtrlV1 {
            get {
                return ResourceManager.GetString("KeyCtrlV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+W.
        /// </summary>
        internal static string KeyCtrlW {
            get {
                return ResourceManager.GetString("KeyCtrlW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        internal static string KeyCtrlW_ {
            get {
                return ResourceManager.GetString("KeyCtrlW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current tab..
        /// </summary>
        internal static string KeyCtrlW__ {
            get {
                return ResourceManager.GetString("KeyCtrlW__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+W.
        /// </summary>
        internal static string KeyCtrlW1 {
            get {
                return ResourceManager.GetString("KeyCtrlW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Win+X.
        /// </summary>
        internal static string KeyCtrlWinX {
            get {
                return ResourceManager.GetString("KeyCtrlWinX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide main window..
        /// </summary>
        internal static string KeyCtrlWinX__ {
            get {
                return ResourceManager.GetString("KeyCtrlWinX__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string KeyDel {
            get {
                return ResourceManager.GetString("KeyDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item(s) which was created by user..
        /// </summary>
        internal static string KeyDel__ {
            get {
                return ResourceManager.GetString("KeyDel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string KeyDel1 {
            get {
                return ResourceManager.GetString("KeyDel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        internal static string KeyEsc {
            get {
                return ResourceManager.GetString("KeyEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter OR go level up OR hide main window..
        /// </summary>
        internal static string KeyEsc__ {
            get {
                return ResourceManager.GetString("KeyEsc__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc (long press).
        /// </summary>
        internal static string KeyEscLong {
            get {
                return ResourceManager.GetString("KeyEscLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide main window..
        /// </summary>
        internal static string KeyEscLong__ {
            get {
                return ResourceManager.GetString("KeyEscLong__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string KeyF1 {
            get {
                return ResourceManager.GetString("KeyF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This help on shortcuts..
        /// </summary>
        internal static string KeyF1__ {
            get {
                return ResourceManager.GetString("KeyF1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10.
        /// </summary>
        internal static string KeyF10 {
            get {
                return ResourceManager.GetString("KeyF10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit from LanExchange program..
        /// </summary>
        internal static string KeyF10__ {
            get {
                return ResourceManager.GetString("KeyF10__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        internal static string KeyF9 {
            get {
                return ResourceManager.GetString("KeyF9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MainForm_Close {
            get {
                return ResourceManager.GetString("MainForm_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MainForm_Information {
            get {
                return ResourceManager.GetString("MainForm_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string MainForm_Legend {
            get {
                return ResourceManager.GetString("MainForm_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Keys.
        /// </summary>
        internal static string mHelpKeys_Text {
            get {
                return ResourceManager.GetString("mHelpKeys_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}.
        /// </summary>
        internal static string PanelPresenter_Items1 {
            get {
                return ResourceManager.GetString("PanelPresenter_Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0} of {1}.
        /// </summary>
        internal static string PanelPresenter_Items2 {
            get {
                return ResourceManager.GetString("PanelPresenter_Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string PanelPresenter_Query {
            get {
                return ResourceManager.GetString("PanelPresenter_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource «{0}» not reachable.
        ///Continue anyway?.
        /// </summary>
        internal static string PanelPresenter_UnreachableMsg {
            get {
                return ResourceManager.GetString("PanelPresenter_UnreachableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Program_Error {
            get {
                return ResourceManager.GetString("Program_Error", resourceCulture);
            }
        }
    }
}
