using System;
using System.ComponentModel;
using System.Windows.Forms;

namespace LanExchange.UI
{
    public class ListViewer : ListView
    {
        public event EventHandler<ColumnClickEventArgs> ColumnRightClick;

        public ListViewer()
        {
            // switch off flikering
            SetStyle(ControlStyles.DoubleBuffer | ControlStyles.OptimizedDoubleBuffer, true);    
        }

        protected override void WndProc(ref Message m)
        {
            const int WM_CONTEXTMENU = 0x007B;

            switch (m.Msg)
            {
                case WM_CONTEXTMENU: 
                    if (!HandleContextMenu(ref m))
                        base.WndProc(ref m);
                    break;
                default:
                    base.WndProc(ref m);
                    break;
            }
        }

        /// <summary>
        /// The user wants to see the context menu.
        /// </summary>
        /// <param name="m">The windows m</param>
        /// <returns>A bool indicating if this m has been handled</returns>
        /// <remarks>
        /// We want to ignore context menu requests that are triggered by right clicks on the header
        /// </remarks>
        protected virtual bool HandleContextMenu(ref Message m)
        {
            // Don't try to handle context menu commands at design time.
            if (DesignMode)
                return false;

            // If the context menu command was generated by the keyboard, LParam will be -1.
            // We don't want to process these.
            if (m.LParam == minusOne)
                return false;

            // If the context menu came from somewhere other than the header control,
            // we also don't want to ignore it
            if (m.WParam != HeaderControl.Handle)
                return false;

            int columnIndex = HeaderControl.ColumnIndexUnderCursor;
            return HandleHeaderRightClick(columnIndex);
        }
        readonly IntPtr minusOne = new IntPtr(-1);

        /// <summary>
        /// Gets the header control for the ListView
        /// </summary>
        [Browsable(false)]
        public HeaderControl HeaderControl
        {
            get { return headerControl ?? (headerControl = new HeaderControl(this)); }
        }
        private HeaderControl headerControl;


        /// <summary>
        /// The user has right clicked on the column headers. Do whatever is required
        /// </summary>
        /// <returns>Return true if this event has been handle</returns>
        protected virtual bool HandleHeaderRightClick(int columnIndex)
        {
            if (ColumnRightClick != null)
            {
                ColumnRightClick(this, new ColumnClickEventArgs(columnIndex));
                return true;
            }
            return false;
        }

    }
}